name: Node CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Setup
      uses: pnpm/action-setup@v1.2.1
      with:
        version: 5.8.0
        run_install: |
          args:
            - --frozen-lockfile
    - name: Lint and Test
      run: |
        pnpm run lint:full
        pnpm run coverage
      env:
        CI: true
